version: '3'

services:
  app:
    container_name: app
    build: '.'
    command: ./entrypoint.sh
    restart: always
    volumes:
      - .:/home/node/api
    depends_on:
      - db
    ports:
      - '3001:3001'
    env_file:
      - '.env'

  db:
    container_name: db
    image: postgres:11
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

volumes:
  pg-data:
